name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
  branches:
    include:
    - master
  tags:
    include:
      - '*'

jobs:
  - job: macOS
    pool:
      name: Default

    steps:
    

    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 
        checkLatest: true

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'
        
    - script: ./msbuild_mono_5_20_1  /p:Configuration=Release SwissAddinKnife/SwissAddinKnife.csproj
      displayName: 'Build SwissAddinKnife'

    - script: ./msbuild_mono_5_20_1  /p:Configuration=Release SwissAddinKnife.Test/SwissAddinKnife.Test.csproj
      displayName: 'Build SwissAddinKnife Test'
       
    - script: /Applications/Visual\ Studio.app/Contents/MacOS/vstool setup pack SwissAddinKnife/bin/Release/net471/SwissAddinKnife.dll
      displayName: 'Build vs4mac Addin'
    
    - script: mv SwissAddinKnife.*.mpack  $(Build.ArtifactStagingDirectory)/
      displayName: 'Copy addin'

    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'Addin'
        targetPath: $(Build.ArtifactStagingDirectory)

    - task: GitHubRelease@0
      inputs:
        gitHubConnection: Connection pipeline
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        target: '$(Build.SourceVersion)'        
        tagSource: 'auto'