#!/bin/sh
MONO_GC_PARAMS="nursery-size=64m,$MONO_GC_PARAMS" exec /Library/Frameworks/Mono.framework/Versions/5.20.1/bin/mono $MONO_OPTIONS /Library/Frameworks/Mono.framework/Versions/5.20.1/lib/mono/msbuild/15.0/bin/MSBuild.dll "$@"
